version: '3'
services:
    node:
      image: library/node
      container_name: zalenium-hangame
      env_file: .env
      command: bash -c "npm install && node random.js"
      volumes:
      - ./:/src
      working_dir: "/src"
