apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-test
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: selenium-test
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 5
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: selenium-test
    spec:
      containers:
      - image: gcr.io/hello-db-a5e51/zalenium-hangame:latest
        imagePullPolicy: Always
        name: zalenium-hangame
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-data
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-data
              key: password
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
