apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - image: gcr.io/hello-db-a5e51/selenium-hub:latest
        imagePullPolicy: Always
        name: selenium-hub
        ports:
          - containerPort: 4444

