apiVersion: v1
kind: Pod
metadata:
  annotations:
  generateName: selenium-test-c79546657-
  labels:
    app: selenium-test
  name: selenium-test
  namespace: default
spec:
  containers:
  - image: gcr.io/hello-db-a5e51/zalenium-hangame:latest
    imagePullPolicy: Always
    name: zalenium-hangame
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 30
      periodSeconds: 10
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-data
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-data
          key: password
    - name: SCMIP
      valueFrom:
        secretKeyRef:
          name: secret-data
          key: scmip
    - name: LOGIN
      valueFrom:
        secretKeyRef:
          name: secret-data
          key: login
    resources:
      requests:
        cpu: 150m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-tq4nm
      readOnly: true
  dnsPolicy: ClusterFirst
  priority: 0
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 10
  volumes:
  - name: default-token-tq4nm
    secret:
      defaultMode: 420
      secretName: default-token-tq4nm
