apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
  namespace: default
spec:
  # Change type according to your choice
  type: LoadBalancer
  ports:
  - name: selenium-hub
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: selenium-hub
